# This is a basic workflow to help you get started with Actions

name: build app

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    
    tags:
      - 'v*.*.*'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_app_32:
    name: Built app 32
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2


      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x86'


      - name: Built app 32
        if: startsWith(github.ref, 'refs/tags/')
        run:  |

          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip
          pip install -r requirements.txt


          

          
          7z.exe a -r 'pikpakdown_${{ github.ref }}_win32.zip' "c:/hostedtoolcache/windows/python/3.8.10/x86/lib/*"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'pikpakdown_${{ github.ref }}_win32.zip'



